In [2]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)
out = np.empty(b.shape)
out.flat = [u*v for (u,v) in b]
out


array([[5., 6., 7.],
       [6., 7., 8.],
       [7., 8., 9.]])

In [2]:
list = []
len(list)


0

In [4]:
arr2=np.delete(arr, np.s_[0:2], 0)
np.squeeze(arr2)

array([ 9, 10, 11, 12])

In [2]:
a=2
for i in range(a):
    print(i)

0
1
2
3
4
